export const leagueLogos: Record<string, string> = {
  'دوري أبطال أوروبا': 'https://upload.wikimedia.org/wikipedia/en/f/f5/UEFA_Champions_League.svg',
  'الدوري الإنجليزي الممتاز': 'https://upload.wikimedia.org/wikipedia/en/f/f2/Premier_League_Logo.svg',
  'الدوري الإنجليزي': 'https://upload.wikimedia.org/wikipedia/en/f/f2/Premier_League_Logo.svg',
  'الدوري الإسباني': 'https://upload.wikimedia.org/wikipedia/commons/0/0f/LaLiga_logo_2023.svg',
  'الدوري الإيطالي': 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Serie_A_logo_2022.svg',
  'الدوري الألماني': 'https://upload.wikimedia.org/wikipedia/en/d/df/Bundesliga_logo_%282017%29.svg',
  'الدوري الفرنسي': 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Ligue_1_2024_Logo.png',
  'كأس العالم': 'https://upload.wikimedia.org/wikipedia/en/1/17/2026_FIFA_World_Cup_emblem.svg',
  'الدوري الهولندي': 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Eredivisie_nieuw_logo_2017-.svg',
  'الدوري البرتغالي': 'https://r2.thesportsdb.com/images/media/league/badge/li05691723186962.png',
  'الدوري البلجيكي': 'https://r2.thesportsdb.com/images/media/league/badge/mjit7n1593634474.png',
  'دوري أبطال أفريقيا': 'https://www.thesportsdb.com/images/media/league/badge/06j61t1597833075.png',
  'الدوري السعودي': 'https://www.thesportsdb.com/images/media/league/badge/8idqms1672322312.png',
  'دوري روشن السعودي': 'https://www.thesportsdb.com/images/media/league/badge/8idqms1672322312.png',
  'الدوري المصري': 'https://www.thesportsdb.com/images/media/league/badge/9a374t1532085773.png',
  'الدوري المغربي': 'https://www.thesportsdb.com/images/media/league/badge/v6o7is1535048866.png',
  'كأس ملك إسبانيا': 'https://www.thesportsdb.com/images/media/league/badge/0a6w6j1514361513.png',
  'كأس الاتحاد الإنجليزي': 'https://www.thesportsdb.com/images/media/league/badge/0x4m8m1514361250.png',
  'كأس إيطاليا': 'https://www.thesportsdb.com/images/media/league/badge/0y7shw1514361569.png',
  'الدوري الأوروبي': 'https://www.thesportsdb.com/images/media/league/badge/8idqms1672322312.png',
  'كأس أمم أفريقيا': 'https://www.thesportsdb.com/images/media/league/badge/06j61t1597833075.png'
};

export const leagueLinks: Record<string, string> = {
  'الدوري الإنجليزي الممتاز': 'https://www.premierleague.com',
  'الدوري الإنجليزي': 'https://www.premierleague.com',
  'الدوري الإسباني': 'https://www.laliga.com',
  'الدوري الإيطالي': 'https://www.legaseriea.it',
  'الدوري الألماني': 'https://www.bundesliga.com',
  'الدوري الفرنسي': 'https://www.ligue1.com',
  'دوري أبطال أوروبا': 'https://www.uefa.com/uefachampionsleague/',
  'Premier League': 'https://www.premierleague.com',
  'La Liga': 'https://www.laliga.com',
  'Serie A': 'https://www.legaseriea.it',
  'Bundesliga': 'https://www.bundesliga.com',
  'Ligue 1': 'https://www.ligue1.com',
  'Champions League': 'https://www.uefa.com/uefachampionsleague/'
};

export const teamLogos: Record<string, string> = {
  // Premier League
  'مانشستر سيتي': 'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg',
  'Manchester City': 'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg',
  'أرسنال': 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
  'Arsenal': 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
  'ليفربول': 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg',
  'Liverpool': 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg',
  'تشيلسي': 'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg',
  'Chelsea': 'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg',
  'مانشستر يونايتد': 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg',
  'Manchester United': 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg',
  'توتنهام': 'https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg',
  'Tottenham Hotspur': 'https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg',
  'أستون فيلا': 'https://upload.wikimedia.org/wikipedia/en/f/f9/Aston_Villa_FC_crest_%282016%29.svg',
  'Aston Villa': 'https://upload.wikimedia.org/wikipedia/en/f/f9/Aston_Villa_FC_crest_%282016%29.svg',
  'نيوكاسل يونايتد': 'https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg',
  'Newcastle United': 'https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg',

  // La Liga
  'ريال مدريد': 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg',
  'Real Madrid': 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg',
  'برشلونة': 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg',
  'FC Barcelona': 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg',
  'أتلتيكو مدريد': 'https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_2017_logo.svg',
  'Atletico Madrid': 'https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_2017_logo.svg',
  'جيرونا': 'https://upload.wikimedia.org/wikipedia/en/9/93/Girona_FC_logo.svg',
  'Girona': 'https://upload.wikimedia.org/wikipedia/en/9/93/Girona_FC_logo.svg',
  'أتلتيك بيلباو': 'https://upload.wikimedia.org/wikipedia/en/9/98/Club_Athletic_Bilbao_logo.svg',
  'Athletic Club': 'https://upload.wikimedia.org/wikipedia/en/9/98/Club_Athletic_Bilbao_logo.svg',
  'ريال سوسيداد': 'https://upload.wikimedia.org/wikipedia/en/f/f1/Real_Sociedad_logo.svg',
  'Real Sociedad': 'https://upload.wikimedia.org/wikipedia/en/f/f1/Real_Sociedad_logo.svg',

  // Serie A
  'إنتر ميلان': 'https://upload.wikimedia.org/wikipedia/en/0/05/FC_Internazionale_Milano_2021.svg',
  'Inter Milan': 'https://upload.wikimedia.org/wikipedia/en/0/05/FC_Internazionale_Milano_2021.svg',
  'ميلان': 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg',
  'AC Milan': 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg',
  'يوفنتوس': 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Juventus_FC_-_pictogram_black_%28Italy%2C_2017%29.svg',
  'Juventus': 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Juventus_FC_-_pictogram_black_%28Italy%2C_2017%29.svg',
  'نابولي': 'https://upload.wikimedia.org/wikipedia/commons/b/ba/SSC_Napoli_2024.svg',
  'Napoli': 'https://upload.wikimedia.org/wikipedia/commons/b/ba/SSC_Napoli_2024.svg',
  'روما': 'https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo_%282017%29.svg',
  'AS Roma': 'https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo_%282017%29.svg',
  'لاتسيو': 'https://upload.wikimedia.org/wikipedia/en/c/ce/S.S._Lazio_badge.svg',
  'Lazio': 'https://upload.wikimedia.org/wikipedia/en/c/ce/S.S._Lazio_badge.svg',

  // Bundesliga
  'بايرن ميونخ': 'https://upload.wikimedia.org/wikipedia/commons/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg',
  'Bayern Munich': 'https://upload.wikimedia.org/wikipedia/commons/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg',
  'بوروسيا دورتموند': 'https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg',
  'Borussia Dortmund': 'https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg',
  'باير ليفركوزن': 'https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg',
  'Bayer Leverkusen': 'https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg',
  'لايبزيج': 'https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg',
  'RB Leipzig': 'https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg',

  // Ligue 1
  'باريس سان جيرمان': 'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg',
  'Paris Saint-Germain': 'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg',
  'مارسيليا': 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Olympique_Marseille_logo.svg',
  'Marseille': 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Olympique_Marseille_logo.svg',
  'ليون': 'https://upload.wikimedia.org/wikipedia/en/c/c6/Olympique_Lyonnais.svg',
  'Lyon': 'https://upload.wikimedia.org/wikipedia/en/c/c6/Olympique_Lyonnais.svg',
  'موناكو': 'https://upload.wikimedia.org/wikipedia/en/4/4c/AS_Monaco_FC.svg',
  'AS Monaco': 'https://upload.wikimedia.org/wikipedia/en/4/4c/AS_Monaco_FC.svg',
  'ليل': 'https://upload.wikimedia.org/wikipedia/en/3/3f/Lille_OSC_2017_logo.svg',
  'Lille': 'https://upload.wikimedia.org/wikipedia/en/3/3f/Lille_OSC_2017_logo.svg',
  'نيس': 'https://upload.wikimedia.org/wikipedia/en/2/2e/OGC_Nice_logo.svg',
  'Nice': 'https://upload.wikimedia.org/wikipedia/en/2/2e/OGC_Nice_logo.svg',
  'لانس': 'https://upload.wikimedia.org/wikipedia/en/c/cc/RC_Lens_logo.svg',
  'Lens': 'https://upload.wikimedia.org/wikipedia/en/c/cc/RC_Lens_logo.svg',
  'رين': 'https://upload.wikimedia.org/wikipedia/en/9/9e/Stade_Rennais_FC.svg',
  'Rennes': 'https://upload.wikimedia.org/wikipedia/en/9/9e/Stade_Rennais_FC.svg',

  // Other UCL / Major
  'بنفيكا': 'https://upload.wikimedia.org/wikipedia/en/a/a2/SL_Benfica_logo.svg',
  'Benfica': 'https://upload.wikimedia.org/wikipedia/en/a/a2/SL_Benfica_logo.svg',
  'بورتو': 'https://upload.wikimedia.org/wikipedia/en/f/f1/FC_Porto.svg',
  'Porto': 'https://upload.wikimedia.org/wikipedia/en/f/f1/FC_Porto.svg',
  'سبورتينغ لشبونة': 'https://upload.wikimedia.org/wikipedia/en/3/3e/Sporting_CP.svg',
  'Sporting CP': 'https://upload.wikimedia.org/wikipedia/en/3/3e/Sporting_CP.svg',
  'أياكس': 'https://upload.wikimedia.org/wikipedia/en/7/79/Ajax_Amsterdam.svg',
  'Ajax': 'https://upload.wikimedia.org/wikipedia/en/7/79/Ajax_Amsterdam.svg',
  'فينورد': 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Feyenoord_logo.svg',
  'Feyenoord': 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Feyenoord_logo.svg',
  'بي إس في آيندهوفن': 'https://upload.wikimedia.org/wikipedia/en/0/05/PSV_Eindhoven.svg',
  'PSV Eindhoven': 'https://upload.wikimedia.org/wikipedia/en/0/05/PSV_Eindhoven.svg',
};
